SELECT * FROM INFORMATION_SCHEMA.TABLES

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

SELECT DISTINCT country FROM gold.dim_customers

SELECT DISTINCT category,subcategory,product_name FROM gold.dim_products
ORDER BY 1,2,3
-- the first parameter of datediff function is the interval
--dimensions
SELECT 
MIN(order_date) as first_order_date,
MAX(order_date) as last_order_date,
DATEDIFF(month,MIN(order_date),MAX(order_date)) as order_range_years
FROM gold.fact_sales

SELECT
MIN(birthdate) AS oldest_birthdate,
datediff(year,MIN(birthdate),GETDATE()) AS oldest_age,
MAX(birthdate) AS youngest_birthdate,
datediff(year,MAX(birthdate),GETDATE()) AS youngest_age
FROM gold.dim_customers

--measures
--find total sales
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales

--how many items are sold 
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales

--find average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales

--find total number of orders
SELECT COUNT(order_number) AS total_orders FROM gold.fact_sales
SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales
SELECT * FROM gold.fact_sales

--find total number of products
SELECT COUNT(product_key) AS total_products FROM gold.dim_products
SELECT COUNT(product_name) AS total_products FROM gold.dim_products
SELECT COUNT(DISTINCT product_key) AS total_products FROM gold.dim_products

--find the total number of customers
SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers

-- find total number of customers that has place an order
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold.fact_sales
SELECT * FROM gold.fact_sales


-- generate a report that shows all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measures FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'AVERAGE PRICE', AVG(price)  FROM gold.fact_sales
UNION ALL
SELECT 'Total number of Orders', COUNT(DISTINCT order_number)  FROM gold.fact_sales
UNION ALL
SELECT 'Total number of Products', COUNT( product_name)  FROM gold.dim_products
UNION ALL
SELECT 'Total number of Customers', COUNT(customer_key)  FROM gold.dim_customers



--magnitude analysis

-- find total customers by countries
SELECT 
country,
COUNT (customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- find total customers by gender
SELECT 
gender,
COUNT (customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC


-- find total products by category
SELECT
category,
COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC




--what is the average costs in each category?
SELECT
category,
AVG(cost) AS average_costs
FROM gold.dim_products
GROUP BY category
ORDER BY average_costs DESC



--what is the total revenue generated for each category?
SELECT
p.category,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC



--find total revenue is generated by each customer?
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC



--What is the distribution of sold items across countries?

SELECT 
c.country,
SUM(f.quantity) as total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.country
ORDER BY total_sold_items DESC

-- ranking analysis
-- Which 5 products generate the highest revenue
SELECT
TOP 5
p.product_name,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

-- What are the 5 worst-performing products in terms of sales?
SELECT
TOP 5
p.product_name,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC

-- best 5 subcategory
SELECT
TOP 5
p.subcategory,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.subcategory
ORDER BY total_revenue DESC

-- use window function
-- Which 5 products generate the highest revenue
SELECT *
FROM(
	SELECT
	p.product_name,
	SUM(f.sales_amount) as total_revenue,
	ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) AS rank_products
	FROM gold.fact_sales f
	LEFT JOIN gold.dim_products p
	ON p.product_key = f.product_key
	GROUP BY p.product_name) t
WHERE rank_products <= 5

--top 10 customers who have generated the highest revenue 
SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) as total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

-- The 3 customers with the fewest orders place
SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) as total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_orders

-- Change Over Time Analysis
SELECT 
YEAR(order_date) as order_year,
SUM(sales_amount) AS total_sales,
COUNT(DISTINCT customer_key) as total_customers,
SUM(quantity) as total_quantity
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY YEAR(order_date)
ORDER BY order_year

SELECT 
MONTH(order_date) as order_month,
SUM(sales_amount) AS total_sales,
COUNT(DISTINCT customer_key) as total_customers,
SUM(quantity) as total_quantity
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY MONTH(order_date)
ORDER BY total_quantity DESC


SELECT 
DATETRUNC(month, order_date) as order_date,
SUM(sales_amount) AS total_sales,
COUNT(DISTINCT customer_key) as total_customers,
SUM(quantity) as total_quantity
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(month, order_date)
ORDER BY DATETRUNC(month, order_date)

SELECT 
DATETRUNC(year, order_date) as order_date,
SUM(sales_amount) AS total_sales,
COUNT(DISTINCT customer_key) as total_customers,
SUM(quantity) as total_quantity
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(year, order_date)
ORDER BY DATETRUNC(year, order_date)


SELECT 
FORMAT(order_date, 'yyyy-MMM') as order_date,
SUM(sales_amount) AS total_sales,
COUNT(DISTINCT customer_key) as total_customers,
SUM(quantity) as total_quantity
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY FORMAT(order_date, 'yyyy-MMM')
ORDER BY FORMAT(order_date, 'yyyy-MMM')

-- calculate the total sales per month
-- and the running total of sales over time
SELECT 
order_date,
total_sales,
SUM(total_sales) OVER (PARTITION BY order_date ORDER BY order_date) as running_total_sales
FROM
(
SELECT 
DATETRUNC(month, order_date) as order_date,
SUM(sales_amount) as total_sales
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(month, order_date) 
) t


-- over years
SELECT 
order_date,
total_sales,
SUM(total_sales) OVER (ORDER BY order_date) as running_total_sales
FROM
(
SELECT 
DATETRUNC(year, order_date) as order_date,
SUM(sales_amount) as total_sales
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(year, order_date) 
) t

-- moving average of the price, progression, how business is growing
SELECT 
order_date,
total_sales,
SUM(total_sales) OVER (ORDER BY order_date) as running_total_sales,
AVG(avg_price) OVER (ORDER BY order_date) as moving_average_price
FROM
(
SELECT 
DATETRUNC(year, order_date) as order_date,
SUM(sales_amount) as total_sales,
AVG(price) AS avg_price
FROM gold.fact_sales
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(year, order_date) 
) t


-- Performance Analysis
/* Analyze the yearly performance of products by comparing their sales
to both the average sales performance of the product and the previous year's sales */

WITH yearly_product_sales AS (
SELECT 
YEAR(f.order_date) AS order_year,
p.product_name,
SUM(f.sales_amount) AS current_sales
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
WHERE f.order_date IS NOT NULL
GROUP BY
YEAR(f.order_date),
p.product_name
)

SELECT 
order_year,
product_name,
current_sales,
AVG (current_sales) OVER (PARTITION BY product_name) as avg_sales,
current_sales - AVG (current_sales)  OVER (PARTITION BY product_name) as diff_avg,
CASE WHEN current_sales - AVG (current_sales)  OVER (PARTITION BY product_name) IS NULL THEN 'N/A'
	WHEN current_sales - AVG (current_sales)  OVER (PARTITION BY product_name) > 0 THEN 'Above Avg'
	WHEN current_sales - AVG (current_sales)  OVER (PARTITION BY product_name) < 0 THEN 'Below Avg'
	ELSE 'AVG'
END AS avg_change,
-- year over year analysis
LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year)  AS previous_year_sales ,
current_sales - LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) AS diff_betwe_pervious_year,
CASE WHEN current_sales - LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) IS NULL THEN 'N/A'
	WHEN current_sales - LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) > 0 THEN 'Increase'
	WHEN current_sales -LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) < 0 THEN 'Decrease'
	ELSE 'No Change'
END AS previous_year_change
FROM yearly_product_sales
ORDER BY product_name, order_year	


--Part-to-whole Analysis
-- which categories contribute the most to overall sales?
WITH category_sales AS(
SELECT
category,
SUM(sales_amount) as total_sales
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY category
)

SELECT
category,
total_sales,
SUM(total_sales) OVER () overall_sales,
CONCAT(ROUND((CAST(total_sales AS FLOAT) / SUM(total_sales) OVER ()) * 100 ,2), '%') AS percent_of_total
FROM category_sales
ORDER BY total_sales DESC

-- Data Segmentation
/*Segment products into cost ranges and count how many products fall into each segment*/
WITH product_segments AS(
SELECT
product_key,
product_name,
cost,
CASE WHEN cost < 100 THEN 'Below 100'
	WHEN cost BETWEEN 100 AND 500 THEN '100-500'
	WHEN cost BETWEEN 501 AND 1000 THEN '501-1000'
	ELSE 'Above 1000'
END AS cost_range
FROM gold.dim_products)


SELECT
cost_range,
COUNT(product_key) AS total_products
FROM product_segments
GROUP BY cost_range
ORDER BY total_products DESC


/*Group customers into three segments based on their spending behavior:
    - VIP: Customers with at least 12 months of history and spending more than €5,000.
    - Regular: Customers with at least 12 months of history but spending €5,000 or less.
    - New: Customers with a lifespan less than 12 months.
And find the total number of customers by each group
*/
WITH customer_spending AS(
SELECT 
c.customer_key,
SUM(f.sales_amount) as total_spending,
MIN(order_date) as first_order,
MAX(order_date) as last_order,
DATEDIFF(month, MIN(order_date), MAX(order_date)) as life_span
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.customer_key
)

-- find the total number of customers by each group

SELECT 
customer_segement,
COUNT (customer_key) as total_customer
FROM(
	SELECT
	customer_key,
	CASE WHEN life_span >= 12 AND total_spending > 5000 THEN 'VIP'
		 WHEN life_span >= 12 AND total_spending <= 5000 THEN 'Regular'
		 ELSE 'NEW'
	END AS customer_segement
	FROM customer_spending) t
GROUP BY customer_segement
ORDER BY total_customer DESC
/*
===============================================================================
Customer Report
===============================================================================
Purpose:
    - This report consolidates key customer metrics and behaviors

Highlights:
    1. Gathers essential fields such as names, ages, and transaction details.
    2. Segments customers into categories (VIP, Regular, New) and age groups.
    3. Aggregates customer-level metrics:
        - total orders
        - total sales
        - total quantity purchased
        - total products
        - lifespan (in months)
    4. Calculates valuable KPIs:
        - recency (months since last order)
        - average order value
        - average monthly spend
===============================================================================
*/
-- 1. Base Query: Retrieves core columns from tables
GO
CREATE VIEW gold.report_customers AS
WITH base_query as (
SELECT
f.order_number ,
f.product_key,
f.order_date,
f.sales_amount,
f.quantity,
c.customer_key,
c.customer_number,
CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
DATEDIFF(year, c.birthdate, GETDATE() ) as age
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
WHERE order_date IS NOT NULL
), customer_aggreagation as(
 --  2. Segments customers into categories (VIP, Regular, New) and age groups.
SELECT 
customer_key,
customer_number,
customer_name,
age,
COUNT(DISTINCT order_number) as total_orders,
SUM(sales_amount) as total_sales,
SUM(quantity) as total_quantity,
COUNT(DISTINCT product_key) as total_products,
MAX(order_date) as last_order_date,
DATEDIFF(month, MIN(order_date), MAX(order_date)) as life_span
FROM
base_query
GROUP BY
customer_key,
customer_number,
customer_name,
age)
--  3. Aggregates customer-level metrics:
SELECT
customer_key,
customer_number,
customer_name,
age,
CASE WHEN age < 20 THEN 'Under 20'
	 WHEN age between 20 and 29 THEN '20-29'
	 WHEN age between 30 and 39 THEN '30-39'
	 WHEN age between 40 and 40 THEN '40-49'
ELSE '50 and above'
END AS age_group,
CASE WHEN life_span >= 12 AND total_sales > 5000 THEN 'VIP'
		 WHEN life_span >= 12 AND total_sales <= 5000 THEN 'Regular'
		 ELSE 'NEW'
	END AS customer_segement,
last_order_date,
/*
 4. Calculates valuable KPIs:
        - recency (months since last order)
        - average order value (total sales / total number of orders)
        - average monthly spend
*/

DATEDIFF(month,last_order_date,GETDATE()) as recency,
total_orders,
total_sales,
total_quantity,
total_products,
life_span,
-- computer average order value (AVO)
CASE WHEN total_sales = 0 THEN 0 
	 ELSE total_sales / total_orders 
END AS avg_order_value,
--computer average monthly spend(total sales / number of months)
CASE WHEN life_span = 0 THEN total_sales 
	 ELSE total_sales / life_span
END AS avg_monthly_spend
FROM customer_aggreagation

-- check the gold report customers
SELECT * FROM gold.report_customers



/*
===============================================================================
Product Report
===============================================================================
Purpose:
    - This report consolidates key product metrics and behaviors.

Highlights:
    1. Gathers essential fields such as product name, category, subcategory, and cost.
    2. Segments products by revenue to identify High-Performers, Mid-Range, or Low-Performers.
    3. Aggregates product-level metrics:
        - total orders
        - total sales
        - total quantity sold
        - total customers (unique)
        - lifespan (in months)
    4. Calculates valuable KPIs:
        - recency (months since last sale)
        - average order revenue (AOR)
        - average monthly revenue
===============================================================================
*/
-- 1. Gathers essential fields such as product name, category, subcategory, and cost.
GO
CREATE VIEW gold.report_products AS
WITH base_query as (
SELECT
	f.order_number ,
	f.order_date,
	f.customer_key,
	f.sales_amount,
	f.quantity,
	p.product_key,
	p.product_name,
	p.category,
	p.subcategory,
	p.cost
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key = p.product_key
WHERE order_date IS NOT NULL
), product_aggreagation as(

--    2. Segments products by revenue to identify High-Performers, Mid-Range, or Low-Performers.
SELECT 
	product_key,
	product_name,
	category,
	subcategory,
	cost,
	DATEDIFF(month, MIN(order_date), MAX(order_date)) as life_span,
	MAX(order_date) as last_sale_date,
	COUNT(DISTINCT order_number) as total_orders,
	COUNT(DISTINCT customer_key) as total_customers,
	SUM(sales_amount) as total_sales,
	SUM(quantity) as total_quantity,
	COUNT(DISTINCT product_key) as total_products,
	ROUND(AVG(CAST(sales_amount as FLOAT) / NULLIF(quantity,0)), 1 ) AS avg_selling_price
	
FROM
base_query
GROUP BY
	product_key,
	product_name,
	category,
	subcategory,
	cost
)
  /*3. Aggregates product-level metrics:
        - total orders
        - total sales
        - total quantity sold
        - total customers (unique)
        - lifespan (in months)
		*/

SELECT
	product_key,
	product_name,
	category,
	subcategory,
	cost,
	last_sale_date,
	DATEDIFF(MONTH,last_sale_date,GETDATE()) as recency_in_months,
	CASE WHEN total_sales > 50000 THEN 'HIGH Performer'
		 WHEN total_sales >= 10000 THEN 'MID RANGE'
		 ELSE 'Low-Performer'
	END AS product_segment,
	life_span,
	total_orders,
	total_customers,
	total_sales,
	total_quantity,
	avg_selling_price,
	-- average order revenue
	CASE 
		 WHEN total_orders = 0 THEN 0
		 ELSE total_sales / total_orders
	END AS avg_order_revenue,
	-- average monthly revenue 
	CASE 
		 WHEN life_span = 0 THEN total_sales
		 ELSE total_sales / life_span
	END AS avg_monthly_revenue

	FROM product_aggreagation


	-- check the final reports generated
	SELECT
	*
	FROM gold.report_products